//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otor.MsixHero.Appx.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otor.MsixHero.Appx.Common.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Packages_Error_DirectoryMissing_Format {
            get {
                return ResourceManager.GetString("Packages_Error_DirectoryMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in MSIX package..
        /// </summary>
        internal static string Packages_Error_FileInsideNotFound {
            get {
                return ResourceManager.GetString("Packages_Error_FileInsideNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Packages_Error_FileMissing_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FileMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string Packages_Error_FileNotFound {
            get {
                return ResourceManager.GetString("Packages_Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string Packages_Error_FileNotFound_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FileNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name must be a string with 5 units, separated by underscores..
        /// </summary>
        internal static string Packages_Error_FullName {
            get {
                return ResourceManager.GetString("Packages_Error_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid full package name. String &apos;{1}&apos; is not a valid package architecture..
        /// </summary>
        internal static string Packages_Error_FullNameInvalid_Architecture_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FullNameInvalid_Architecture_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid full package name. String &apos;{1}&apos; is not a valid publisher hash..
        /// </summary>
        internal static string Packages_Error_FullNameInvalid_Hash_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FullNameInvalid_Hash_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid full package name. String &apos;{1}&apos; is not a valid version..
        /// </summary>
        internal static string Packages_Error_FullNameInvalid_Version_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FullNameInvalid_Version_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder does not contain APPX/MSIX package nor APPX bundle..
        /// </summary>
        internal static string Packages_Error_NoPackageInFolder {
            get {
                return ResourceManager.GetString("Packages_Error_NoPackageInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not an MSIX/APPX package, or the content of the package is damaged..
        /// </summary>
        internal static string Packages_Error_NotAPackage {
            get {
                return ResourceManager.GetString("Packages_Error_NotAPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required package..
        /// </summary>
        internal static string Packages_Error_PackageNotFound {
            get {
                return ResourceManager.GetString("Packages_Error_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 + AI.
        /// </summary>
        internal static string Packages_Types_AiStub {
            get {
                return ResourceManager.GetString("Packages_Types_AiStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Win32 app enhanced by Advanced Installer launcher.
        /// </summary>
        internal static string Packages_Types_AiStub_Long {
            get {
                return ResourceManager.GetString("Packages_Types_AiStub_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string Packages_Types_AiStub_Short {
            get {
                return ResourceManager.GetString("Packages_Types_AiStub_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string Packages_Types_App {
            get {
                return ResourceManager.GetString("Packages_Types_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        internal static string Packages_Types_Framework {
            get {
                return ResourceManager.GetString("Packages_Types_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 + MSIX Helper.
        /// </summary>
        internal static string Packages_Types_MsixHelper {
            get {
                return ResourceManager.GetString("Packages_Types_MsixHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Win32 app enhanced by MSIX Helper.
        /// </summary>
        internal static string Packages_Types_MsixHelper_Long {
            get {
                return ResourceManager.GetString("Packages_Types_MsixHelper_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSIX Helper.
        /// </summary>
        internal static string Packages_Types_MsixHelper_Short {
            get {
                return ResourceManager.GetString("Packages_Types_MsixHelper_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 + PSF.
        /// </summary>
        internal static string Packages_Types_Psf {
            get {
                return ResourceManager.GetString("Packages_Types_Psf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Win32 app enhanced by Package Support Framework (PSF).
        /// </summary>
        internal static string Packages_Types_Psf_Long {
            get {
                return ResourceManager.GetString("Packages_Types_Psf_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSF.
        /// </summary>
        internal static string Packages_Types_Psf_Short {
            get {
                return ResourceManager.GetString("Packages_Types_Psf_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWA.
        /// </summary>
        internal static string Packages_Types_Pwa {
            get {
                return ResourceManager.GetString("Packages_Types_Pwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive Web Application.
        /// </summary>
        internal static string Packages_Types_Pwa_Long {
            get {
                return ResourceManager.GetString("Packages_Types_Pwa_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Packages_Types_Unknown {
            get {
                return ResourceManager.GetString("Packages_Types_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP.
        /// </summary>
        internal static string Packages_Types_UWP {
            get {
                return ResourceManager.GetString("Packages_Types_UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Windows Platform (UWP) app.
        /// </summary>
        internal static string Packages_Types_UWP_Long {
            get {
                return ResourceManager.GetString("Packages_Types_UWP_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32.
        /// </summary>
        internal static string Packages_Types_W32 {
            get {
                return ResourceManager.GetString("Packages_Types_W32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Win32 app.
        /// </summary>
        internal static string Packages_Types_W32_Long {
            get {
                return ResourceManager.GetString("Packages_Types_W32_Long", resourceCulture);
            }
        }
    }
}
