//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otor.MsixHero.Appx.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otor.MsixHero.Appx.Editor.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; is not supported..
        /// </summary>
        public static string AppxEditor_Error_CommandNotSupported_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Error_CommandNotSupported_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a custom capability must be longer than {2} characters. Capability &apos;{0}&apos; has only {1} characters..
        /// </summary>
        public static string AppxEditor_Error_CustomCapabilityLength_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Error_CustomCapabilityLength_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document root cannot be empty..
        /// </summary>
        public static string AppxEditor_Error_EmptyRoot {
            get {
                return ResourceManager.GetString("AppxEditor_Error_EmptyRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist..
        /// </summary>
        public static string AppxEditor_Error_FileMissing_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Error_FileMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry hive {0} is not supported..
        /// </summary>
        public static string AppxEditor_Error_HiveNotSupported_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Error_HiveNotSupported_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest file cannot be removed..
        /// </summary>
        public static string AppxEditor_Error_ManifestCannotBeRemoved {
            get {
                return ResourceManager.GetString("AppxEditor_Error_ManifestCannotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest file not found in &apos;{0}&apos;..
        /// </summary>
        public static string AppxEditor_Error_ManifestNotFound_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Error_ManifestNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid version string..
        /// </summary>
        public static string AppxEditor_Error_NotAVersion_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Error_NotAVersion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path must be a registry path..
        /// </summary>
        public static string AppxEditor_Error_PathNoRegFile {
            get {
                return ResourceManager.GetString("AppxEditor_Error_PathNoRegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file from &apos;{0}&apos; to &apos;{1}&apos;....
        /// </summary>
        public static string AppxEditor_Files_Copy_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Files_Copy_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;ProcessorArchitecture&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Identity_ChangingArchitecture_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_ChangingArchitecture_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;Name&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Identity_ChangingName_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_ChangingName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;Publisher&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Identity_ChangingPublisher_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_ChangingPublisher_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;ResourceId&apos; from &apos;{0}&apos; to &apos;{1}&apos;....
        /// </summary>
        public static string AppxEditor_Identity_ChangingResourceId_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_ChangingResourceId_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;Version&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Identity_ChangingVersion_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_ChangingVersion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;ProcessorArchitecture&apos; to &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Identity_SettingArchitecture_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_SettingArchitecture_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;Name&apos; to &apos;{0}&apos;....
        /// </summary>
        public static string AppxEditor_Identity_SettingName_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_SettingName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;Publisher&apos; to &apos;{0}&apos;....
        /// </summary>
        public static string AppxEditor_Identity_SettingPublisher_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_SettingPublisher_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;ResourceId&apos; to &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Identity_SettingResourceId_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_SettingResourceId_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;Version&apos; to &apos;{0}&apos;....
        /// </summary>
        public static string AppxEditor_Identity_SettingVersion_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Identity_SettingVersion_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;Description&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_ChangingDescription_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_ChangingDescription_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;DisplayName&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_ChangingDisplayName_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_ChangingDisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;Logo&apos; from &apos;{0}&apos; to &apos;{1}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_ChangingLogo_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_ChangingLogo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing property &apos;ModificationPackage&apos; from &apos;{0}&apos; to &apos;true&apos;….
        /// </summary>
        public static string AppxEditor_Properties_ChangingModPackTrue_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_ChangingModPackTrue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing attribute &apos;PublisherDisplayName&apos; from &apos;{0}&apos; to &apos;{1}&apos;....
        /// </summary>
        public static string AppxEditor_Properties_ChangingPublisherDisplayName_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_ChangingPublisherDisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing property &apos;ModificationPackage&apos;….
        /// </summary>
        public static string AppxEditor_Properties_RemovingModPack {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_RemovingModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property &apos;Description&apos; to &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_SettingDescription_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_SettingDescription_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;DisplayName&apos; to &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_SettingDisplayName_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_SettingDisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;Logo&apos; to &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_SettingLogo_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_SettingLogo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property &apos;ModificationPackage&apos; to &apos;true&apos;….
        /// </summary>
        public static string AppxEditor_Properties_SettingModPackTrue {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_SettingModPackTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting attribute &apos;PublisherDisplayName&apos; to &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Properties_SettingPublisherDisplayName_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Properties_SettingPublisherDisplayName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing registry file &apos;{0}&apos;….
        /// </summary>
        public static string AppxEditor_Registry_ImportingRegFile_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Registry_ImportingRegFile_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key has been successfully imported..
        /// </summary>
        public static string AppxEditor_Registry_ImportSuccess {
            get {
                return ResourceManager.GetString("AppxEditor_Registry_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key &apos;{0}\{1}&apos; has been set..
        /// </summary>
        public static string AppxEditor_Registry_RegKeySet_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Registry_RegKeySet_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry value &apos;{0}&apos; = &apos;{1}&apos; ({3}) has been set in &apos;{4}\{5}.
        /// </summary>
        public static string AppxEditor_Registry_RegValueSet_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Registry_RegValueSet_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing registry key &apos;{0}\{1}&apos;….
        /// </summary>
        public static string AppxEditor_Registry_RemovingKey_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Registry_RemovingKey_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing value &apos;{0}&apos; from key &apos;{1}\{2}&apos;....
        /// </summary>
        public static string AppxEditor_Registry_RemovingValue_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Registry_RemovingValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capability &apos;{0}&apos; already exists and will not be added again..
        /// </summary>
        public static string AppxEditor_Warn_CapabilityExists_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Warn_CapabilityExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; could not be removed ({1})..
        /// </summary>
        public static string AppxEditor_Warn_FileCouldNotRemove_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Warn_FileCouldNotRemove_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of the path &apos;{0}&apos; does not exist..
        /// </summary>
        public static string AppxEditor_Warn_FilePath_PartMissing_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Warn_FilePath_PartMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes have been applied. Registry key &apos;{0}\{1}&apos; does not exist..
        /// </summary>
        public static string AppxEditor_Warn_NoChangesDueToMissingKey_Format {
            get {
                return ResourceManager.GetString("AppxEditor_Warn_NoChangesDueToMissingKey_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been removed..
        /// </summary>
        public static string AppxEditor_Warn_NoFileRemoved {
            get {
                return ResourceManager.GetString("AppxEditor_Warn_NoFileRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new entries have been imported..
        /// </summary>
        public static string AppxEditor_Warn_NothingImported {
            get {
                return ResourceManager.GetString("AppxEditor_Warn_NothingImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot end with dot..
        /// </summary>
        public static string Validation_Appx_CannotEndWithDot {
            get {
                return ResourceManager.GetString("Validation_Appx_CannotEndWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package name cannot be empty..
        /// </summary>
        public static string Validation_Appx_PackageName_Empty {
            get {
                return ResourceManager.GetString("Validation_Appx_PackageName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package name must consist of alpha-numeric, period and dash characters..
        /// </summary>
        public static string Validation_Appx_PackageName_WrongChars {
            get {
                return ResourceManager.GetString("Validation_Appx_PackageName_WrongChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package name must be a string between 3 and 50 characters in length..
        /// </summary>
        public static string Validation_Appx_PackageName_WrongLength {
            get {
                return ResourceManager.GetString("Validation_Appx_PackageName_WrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher cannot be empty..
        /// </summary>
        public static string Validation_Appx_Publisher_Empty {
            get {
                return ResourceManager.GetString("Validation_Appx_Publisher_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher name must be a valid DN string (for example CN=Author).
        /// </summary>
        public static string Validation_Appx_Publisher_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_Appx_Publisher_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource ID cannot be empty..
        /// </summary>
        public static string Validation_Appx_ResourceId_Empty {
            get {
                return ResourceManager.GetString("Validation_Appx_ResourceId_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource ID must consist of alpha-numeric, period and dash characters..
        /// </summary>
        public static string Validation_Appx_ResourceId_WrongChars {
            get {
                return ResourceManager.GetString("Validation_Appx_ResourceId_WrongChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource ID must be a string between 1 and 30 characters in length..
        /// </summary>
        public static string Validation_Appx_ResourceId_WrongLength {
            get {
                return ResourceManager.GetString("Validation_Appx_ResourceId_WrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; starts with a restricted prefix &apos;{0}&apos;..
        /// </summary>
        public static string Validation_Appx_RestrictedPrefix {
            get {
                return ResourceManager.GetString("Validation_Appx_RestrictedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is a restricted name and cannot be used..
        /// </summary>
        public static string Validation_Appx_RestrictedValue {
            get {
                return ResourceManager.GetString("Validation_Appx_RestrictedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; contains a restricted string &apos;.xn--&apos;..
        /// </summary>
        public static string Validation_Appx_RestrictedXnString {
            get {
                return ResourceManager.GetString("Validation_Appx_RestrictedXnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version cannot be empty..
        /// </summary>
        public static string Validation_Appx_Version_Empty {
            get {
                return ResourceManager.GetString("Validation_Appx_Version_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version must be in format #.#.#.#..
        /// </summary>
        public static string Validation_Appx_Version_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_Appx_Version_InvalidFormat", resourceCulture);
            }
        }
    }
}
