//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otor.MsixHero.Appx.Reader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otor.MsixHero.Appx.Reader.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles are not supported..
        /// </summary>
        internal static string Packages_Error_BundleNotSupported {
            get {
                return ResourceManager.GetString("Packages_Error_BundleNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Packages_Error_DirectoryMissing_Format {
            get {
                return ResourceManager.GetString("Packages_Error_DirectoryMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in MSIX package..
        /// </summary>
        internal static string Packages_Error_FileInsideNotFound {
            get {
                return ResourceManager.GetString("Packages_Error_FileInsideNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Packages_Error_FileMissing_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FileMissing_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string Packages_Error_FileNotFound {
            get {
                return ResourceManager.GetString("Packages_Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string Packages_Error_FileNotFound_Format {
            get {
                return ResourceManager.GetString("Packages_Error_FileNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest is malformed, missing &lt;Identity /&gt;..
        /// </summary>
        internal static string Packages_Error_Manifest_Identity {
            get {
                return ResourceManager.GetString("Packages_Error_Manifest_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest is malformed. There is no root element..
        /// </summary>
        internal static string Packages_Error_Manifest_Root {
            get {
                return ResourceManager.GetString("Packages_Error_Manifest_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest is malformed. The document root must be &lt;Package /&gt; element..
        /// </summary>
        internal static string Packages_Error_Manifest_Root_Package {
            get {
                return ResourceManager.GetString("Packages_Error_Manifest_Root_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest is malformed. The document root must be &lt;Package /&gt; element, belonging to a supported namespace..
        /// </summary>
        internal static string Packages_Error_Manifest_Root_Package_Namespace {
            get {
                return ResourceManager.GetString("Packages_Error_Manifest_Root_Package_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder does not contain APPX/MSIX package nor APPX bundle..
        /// </summary>
        internal static string Packages_Error_NoPackageInFolder {
            get {
                return ResourceManager.GetString("Packages_Error_NoPackageInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not an MSIX/APPX package, or the content of the package is damaged..
        /// </summary>
        internal static string Packages_Error_NotAPackage {
            get {
                return ResourceManager.GetString("Packages_Error_NotAPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required package..
        /// </summary>
        internal static string Packages_Error_PackageNotFound {
            get {
                return ResourceManager.GetString("Packages_Error_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required package source is not supported..
        /// </summary>
        internal static string Packages_Error_SrcNotSupported {
            get {
                return ResourceManager.GetString("Packages_Error_SrcNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PackageDirectory&gt;.
        /// </summary>
        internal static string Packages_PkgDir_Placeholder {
            get {
                return ResourceManager.GetString("Packages_PkgDir_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PackageDrive&gt;.
        /// </summary>
        internal static string Packages_PkgDrv_Placeholder {
            get {
                return ResourceManager.GetString("Packages_PkgDrv_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with extension {0}.
        /// </summary>
        internal static string Packages_Psf_FilesWithExt_Format {
            get {
                return ResourceManager.GetString("Packages_Psf_FilesWithExt_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string Psf_Descriptor_AllFiles {
            get {
                return ResourceManager.GetString("Psf_Descriptor_AllFiles", resourceCulture);
            }
        }
    }
}
